name: 打包web,上传oss
on:
  push:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: upload files to OSS
        uses: fangbinwei/aliyun-oss-website-action@v1
        with:
          accessKeyId: ${{ secrets.ALIYUN_OSS_ACCESS_KEY_ID }}
          accessKeySecret: ${{ secrets.ALIYUN_OSS_ACCESS_KEY_SECRET }}
          bucket: agamotto-web/main
          endpoint: oss-cn-shanghai.aliyuncs.com
          folder: "dist"
    
